name: Build and Push to ECR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
env:
  AWS_REGION: us-east-1
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::097324129341:role/GitHubAction-AssumeRoleWithAction
        role-session-name: GitHubActions
        aws-region: us-east-1

    - name: Build, tag, and push image
      env:
        ECR_REGISTRY: 097324129341.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: /demo/eks-websocket-loadtest
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
